### ISSUE TITLE
[Suggestion] The rom contains cloud catcher.

### ISSUE THREAD

**Issue by Darkodaaa** [SwitchCraftCC/sc3-rom#11]
This https://cloud-catcher.squiddev.cc/

**Comment by Darkodaaa** [comment]
Sry for dump request.

**Comment by Kan18** [comment]
But it already does lol https://github.com/SwitchCraftCC/sc3-rom/blob/1.19.3/switchcraft/data/computercraft/lua/rom/programs/cloud.lua

**Comment by Darkodaaa** [comment]
B
