### ISSUE TITLE
Import won't throw error when importing invalid file.

### ISSUE THREAD

**Issue by Darkodaaa** [SwitchCraftCC/sc3-rom#12]
I imported a file called "Lobby Music.dfpwm", and now my NI has a file i can't rename/delete/move/use, because it has a space in its filename.
![image](https://github.com/SwitchCraftCC/sc3-rom/assets/94637181/a0edccc6-7bda-407f-93c4-eef931f8dea1)

**Comment by Kan18** [comment]
type `rm "Lobby Music.dfpwm"`

**Comment by ZeanZarzin** [comment]
if that doesn't work, also try `rm Lobby\ Music.dfpwm`, but it should work
