### ISSUE TITLE
Add password support to pastebin

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/sc3-rom#9]
I have a fork ready to PR if you guys want. 
I even updated the usages
[Here it is](https://github.com/scmcgowen/sc3-rom/blob/1.19.3/switchcraft/data/computercraft/lua/rom/programs/http/pastebin.lua)

**Comment by Lemmmy** [comment]
Thanks, could you open a PR? We have a few comments we'd like to leave in a code review

**Comment by scmcgowen** [comment]
Pull request sent
